apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: mastofx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mastofx
    app.kubernetes.io/part-of: mastofx
  name: mastofx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: mastofx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: mastofx
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-engineering-hrup-tenant/mastofx/mastofx@sha256:5843bbce57be86c325ebb5189a0c2a7528f31793f66bba1f2f0c6232e0884030
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
