apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: mastofx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mastofx
    app.kubernetes.io/part-of: mastofx
  name: mastofx2bww
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: mastofx
    weight: null
status: {}
